trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Correct key name: vmImage instead of VmImage

steps:
- script: git clone https://github.com/mohammadsyed397/shell_scripts
  displayName: 'Cloning the code'

- script: ./diskutilization.sh
  displayName: 'Check the disk utilization'
