trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Correct key name: vmImage instead of VmImage

steps:
- script: git clone https://github.com/mohammadsyed397/shell_scripts
  displayName: 'Cloning the code'

- script: |
    chmod +x ./shell_scripts/disk_utilization.sh
    ./shell_scripts/disk_utilization.sh
  displayName: 'Make diskutilization.sh executable and run it'
